version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: employee-postgres
    environment:
      POSTGRES_DB: employee_app
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: employee123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: employee-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://employee-postgres:5432/employee_app
      SPRING_DATASOURCE_USERNAME: employee
      SPRING_DATASOURCE_PASSWORD: employee123

volumes:
  pgdata:
